# logging.properties
handlers = java.util.logging.ConsoleHandler
.level = INFO
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Mute Mojarra/JSF (serious errors only)
jakarta.enterprise.resource.webcontainer.faces.lifecycle.level = SEVERE
jakarta.faces.level = SEVERE
com.sun.faces.level = SEVERE

# Only show our logs (CustomExceptionHandler)
com.taskimed.config.CustomExceptionHandler.level = ALL
