package com.taskimed.beans;

import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;
import jakarta.faces.application.FacesMessage;
import jakarta.faces.context.FacesContext;
import jakarta.annotation.PostConstruct;
import org.primefaces.PrimeFaces;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.taskimed.config.Util;
import com.taskimed.dto.TeamDTO;
import com.taskimed.dto.UserDTO;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Bean responsible for managing users (User entity) in the JSF interface.
 * Includes CRUD operations and user invitation handling through REST services.
 */
@Data
@Named
@SessionScoped
@EqualsAndHashCode(callSuper = false)
public class UserBean extends EntityLazyBean<UserDTO> implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Util util = new Util();
    private UserDTO selectedUser = new UserDTO();
    private String action;
    private String inviteUrl; // URL generated by the invitation
    private List<UserDTO> users;
    private List<TeamDTO> teams;

    @Override
    public String getEndpoint() {
        return "/api/users/paginated";
    }

    @Override
    public Class<UserDTO> getEntityClass() {
        return UserDTO.class;
    }

    @PostConstruct
    public void initBean() {
        super.init();
        try {
            String token = util.obtenerToken();
            users = util.getDataFromService("/api/users", new TypeReference<List<UserDTO>>() {}, token);
            teams = util.getDataFromService("/api/teams", new TypeReference<List<TeamDTO>>() {}, token);
        } catch (Exception e) {
            e.printStackTrace();
            users = List.of();
        }
    }

    public void ejecutar() {
        if ("Create".equals(action))
            create();
        else if ("Update".equals(action))
            update();
    }

    public List<UserDTO> getUsers() {
        return users;
    }

    public void ejecutar(String accion) throws Exception {
        if ("eliminar".equals(accion)) {
            util.deleteDataFromService("/api/users/", selectedUser.getId(), token);
        } else if ("crear".equals(accion) || "actualizar".equals(accion)) {

            // ✅ Send data without password to the backend
            selectedUser.setPassword(null);

            UserDTO user = util.postDataToService(
                "/api/users",
                selectedUser,
                new TypeReference<UserDTO>() {},
                token
            );

            selectedUser.setId(user.getId());

            // ✅ Automatically generate invitation after user creation
            if ("crear".equals(accion) && user.getId() != null) {
                try {
                    Map<String, Object> response = util.postDataToService(
                        "/api/users/invite/" + user.getId(),
                        null,
                        new TypeReference<Map<String, Object>>() {},
                        token
                    );

                    System.out.println(">>> Invitation generated for user ID: " + user.getId());

                    this.inviteUrl = (String) response.get("inviteUrl");

                    FacesContext.getCurrentInstance().addMessage(null,
                        new FacesMessage(FacesMessage.SEVERITY_INFO,
                            "Invitation generated",
                            "Link sent by email. It expires in 3 minutes."
                        )
                    );
                    PrimeFaces.current().ajax().update("frmNewEdit:invitePanel");

                } catch (Exception e) {
                    FacesContext.getCurrentInstance().addMessage(null,
                        new FacesMessage(FacesMessage.SEVERITY_ERROR,
                            "Error",
                            "User created, but the invitation could not be generated."
                        )
                    );
                    e.printStackTrace();
                }
            }
        }
    }

    public void clear() {
        selectedUser = new UserDTO();
        action = null;
        inviteUrl = null;
    }

    private void create() {
        try {
            ejecutar("crear");
            FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO,
                    "Success", "User created successfully. Status: " + util.getStatus()));
            PrimeFaces.current().ajax().update("form:datatable");
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_FATAL,
                    "Error", "The user could not be created."));
            e.printStackTrace();
        }
    }

    private void update() {
        try {
            ejecutar("actualizar");
            FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_INFO,
                    "Success", "User updated successfully. Status: " + util.getStatus()));
            PrimeFaces.current().ajax().update("form:datatable");
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_FATAL,
                    "Error", "The user could not be updated."));
            e.printStackTrace();
        }
    }

    public void delete() {
        try {
            ejecutar("eliminar");
            if (util.getStatus() == 403) {
                FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                        "Warning", "The authenticated user cannot be deleted."));
                return;
            }
            if (util.getStatus() < 400) {
                FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_INFO,
                        "Success", "User deleted successfully. Status: " + util.getStatus()));
                adjustPaginatorAfterDeletion("tableEntity", lazyModel);
            }
        } catch (Exception e) {
            FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_FATAL,
                    "Error", "There was a problem deleting the user."));
            e.printStackTrace();
        }
    }
    public void validateEmail() {
        if (selectedUser.getEmail() == null || selectedUser.getEmail().trim().isEmpty()) {
            FacesContext.getCurrentInstance().addMessage("frmNewEdit:email",
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Email is required.", null));
            return;
        }

        String regex = "^[A-Za-z0-9+_.-]+@(?:[A-Za-z0-9-]+\\.)+[A-Za-z]{2,6}$";

        if (!selectedUser.getEmail().matches(regex)) {
            FacesContext.getCurrentInstance().addMessage("frmNewEdit:email",
                    new FacesMessage(FacesMessage.SEVERITY_ERROR, "Invalid email format.", null));
        }
    }
}
